project:
  type: website
  output-dir: docs
  resources:
    - files/cv-konya.pdf

website:
  title: "István Kónya"
  favicon: files/ik.png

  navbar:
    title: "Home"
    pinned: true
    left:
      - href: work.qmd
        text: Work in progress
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: flatly
    max-width: 1100px
    toc: false
    smooth-scroll: true